export const UPDATE_CURRENCIES_RATES = "UPDATE_CURRENCIES_RATES";
export const EXPENSES_ADD = "EXPENSES_ADD";
export const EXPENSES_DELETE = "EXPENSES_DELETE";
export const REQUEST_CURRENCIES_RATES = "REQUEST_CURRENCIES_RATES";
export const ERROR_CURRENCIES_RATES = "ERROR_CURRENCIES_RATES";



